export const EXPORT_HEADS = [
  "OCEAN_FREIGHT",
  "AIR_FREIGHT",
  "ON_CARRIAGE",
  "DDC",
  "THC",
  "BL_CHARGES",
  "SEAL_CHARGES",
  "MOVEMENT",
  "MEASUREMENT",
  "CUSTOM_CLEARING",
  "EDIC_EGM",
  "TR_SUBMISSION",
  "VGM",
  "DUTY_DRAWBACK",
  "RAILWAY",
  "WAREHOUSE",
  "TRANSPORTATION",
  "COO_GSP",
  "LABOUR",
  "SHUT_OUT",
  "COURIER",
  "FUMIGATION",
  "DOCUMENTATION",
  "MISC",
];

export const IMPORT_HEADS = [
  "OCEAN_FREIGHT",
  "AIR_FREIGHT",
  "ON_CARRIAGE",
  "THC",
  "DELIVERY_ORDER",
  "LINER_DETENTION",
  "CUSTOM_CLEARING",
  "VGM",
  "EDIC",
  "IMPORT_CUSTOM_DUTY",
  "STAMP_DUTY",
  "WAREHOUSE",
  "LABOUR",
  "TR_CHALLAN",
  "HANDLING",
  "LICENSE_FEES",
  "PHYTO",
  "TRANSPORTATION",
  "SECURITY",
  "CHARTERED_ENGINEER",
  "DECONSOLIDATION",
  "MANIFESTATION",
  "COURIER",
  "DOCUMENTATION",
  "MISC",
];

/* 👇 DISPLAY LABELS (VERY IMPORTANT) */
export const EXPENDITURE_LABELS = {
  OCEAN_AIR_FREIGHT: "Ocean / Air Freight",
  ON_CARRIAGE: "On Carriage",
  DDC: "DDC",
  THC: "Terminal Handling Charges",
  BL_CHARGES: "B/L Charges",
  SEAL_CHARGES: "Seal Charges",
  MOVEMENT: "Movement (Lift On / Off)",
  MEASUREMENT: "Measurement Charges",
  CUSTOM_CLEARING: "Custom Clearing Charges",
  EDIC_EGM: "EDIC / EGM Charges",
  TR_SUBMISSION: "T.R. Submission",
  VGM: "VGM Charges",
  DUTY_DRAWBACK: "Duty Drawback",
  RAILWAY: "Railway Charges",
  WAREHOUSE: "Warehouse Charges",
  TRANSPORTATION: "Transportation",
  COO_GSP: "Certificate of Origin / GSP",
  LABOUR: "Labour Charges",
  SHUT_OUT: "Shut Out Charges",
  COURIER: "Courier Charges",
  FUMIGATION: "Fumigation",
  MISC: "Miscellaneous",

  DELIVERY_ORDER: "Delivery Order",
  LINER_DETENTION: "Liner Detention",
  EDIC: "EDIC Charges",
  IMPORT_CUSTOM_DUTY: "Import Custom Duty",
  STAMP_DUTY: "Stamp Duty",
  TR_CHALLAN: "T.R. & Challan",
  HANDLING: "Handling Charges",
  LICENSE_FEES: "License / EPCG / DEPB Fees",
  PHYTO: "Phytosanitary Charges",
  SECURITY: "Security Charges",
  CHARTERED_ENGINEER: "Chartered Engineer Certificate",
  DECONSOLIDATION: "De-consolidation Charges",
  MANIFESTATION: "Manifestation Charges",
};
